name: CI Workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_Job:
    runs-on : windows-latest
    #ubuntu-latest
    #windows-latest
    #macos-latest
    steps:
      - name : Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21.0.7'

      - name: Build with Maven
        run: mvn clean install

  sonar_analysis:
    runs-on: windows-latest
    needs: build_job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21.0.7'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
            path: ~/.m2
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-

      - name: Build with tests and generate JaCoCo report
        run: mvn clean verify

      - name: Run SonarCloud analysis
        run: mvn sonar:sonar -Dsonar.projectKey=testing551_junit -Dsonar.organization=testing551 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.coverage.jacoco.reportPaths=target/site/jacoco/jacoco.xml

      - name: Print SonarCloud URL
        run: |
          echo "View SonarCloud analysis results here: https://sonarcloud.io/dashboard?id=testing551_junit"
      



